import { useCallback } from "react";
import { Upload } from "lucide-react";

export default function FileUpload({ onData }) {
  const handleFile = useCallback(
    (e) => {
      const file = e.target.files?.[0];
      if (!file) return;

      const reader = new FileReader();
      reader.onload = (evt) => {
        try {
          const parsed = JSON.parse(evt.target.result);
          onData(parsed);
        } catch {
          alert("Invalid JSON file. Please upload the simulation output JSON.");
        }
      };
      reader.readAsText(file);
    },
    [onData],
  );

  return (
    <div className="flex flex-col items-center justify-center py-20">
      <div className="bg-white rounded-xl shadow-md border border-gray-200 p-12 text-center max-w-md">
        <Upload className="w-12 h-12 text-indigo-400 mx-auto mb-4" />
        <h2 className="text-lg font-medium text-gray-800 mb-2">
          Upload Simulation Results
        </h2>
        <p className="text-sm text-gray-500 mb-6">
          Upload the JSON file generated by{" "}
          <code className="bg-gray-100 px-1 rounded text-xs">
            receipt-sim --json output.json
          </code>
        </p>
        <label className="inline-flex items-center gap-2 px-5 py-2.5 bg-indigo-600 text-white rounded-lg cursor-pointer hover:bg-indigo-700 transition-colors text-sm font-medium">
          <Upload className="w-4 h-4" />
          Choose File
          <input
            type="file"
            accept=".json"
            onChange={handleFile}
            className="hidden"
          />
        </label>
      </div>
    </div>
  );
}
